version: "3.7"

services:
  mongo_db:
    container_name: mongo
    image: "mongo:4.4.3"
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data:
